# Push Firewall Object 
---

- name: Palo Alto FW Object creation
  hosts: palo
  connection: local

  collections:
    - paloaltonetworks.panos
 
  tasks: 

    - name: Grab credentials from vault
      include_vars: '../inventory/group_vars/palo.yml'
      no_log: 'yes'

    - name: Create first object '{{ objecta }}'
      panos_address_object:
        provider: '{{ palo_provider }}'
        name: '{{ objecta }}'
        value: '{{ objecta_value }}'
        description: '{{ objecta }}' 
        tag: ['Prod']

    - name: commit candidate config on firewalls.
      panos_commit:
        provider: '{{ palo_provider }}'



    



